### ISSUE TITLE
Standalone SDK build for 1.7 fails to compile applications

### ISSUE THREAD

**Issue by 17twenty** [gumstix/Gumstix-YoctoProject-Repo#58]
Generated a toolchain using  bitbake -c populate_sdk gumstix-console-image as standard for Yocto builds and it fails to produce a usable cross-compiler.

$ cat helloworld.c 
#include <stdio.h>

int main()
{
  printf("Hello World\n");
  return 0;
}

$ arm-poky-linux-gnueabi-gcc helloworld.c -o helloworld
In file included from /opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi/usr/include/features.h:389:0,
                 from /opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi/usr/include/stdio.h:27,
                 from helloworld.c:1:
/opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
 # include <gnu/stubs-soft.h>
                             ^
compilation terminated.

--

Interestingly the env does show the following flags:
KCFLAGS=--sysroot=/opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi
CXX=arm-poky-linux-gnueabi-g++  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a8 --sysroot=/opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi
CC=arm-poky-linux-gnueabi-gcc  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a8 --sysroot=/opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueab

Doing the following *does* result in a complete build but this isn't how most SDKs perform - even when sourcing the environment:

$ arm-poky-linux-gnueabi-gcc  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a8 --sysroot=/opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi helloworld.c -o helloworld

or 

$ $CC helloworld.c -o helloworld

**Comment by ashcharles** [comment]
This actually looks like correct behaviour---I would expect to use $CC in a
Makefile etc. not the full cross-compiler executable
arm-poky-linux-gnueabi-gcc.  This way, I don't have to pass sysroot paths
etc. either although [1] shows that the meta-toolchain target would provide
a more minimal setup.  In this case, the executable needs to know about the
abi mode (hard vs softfp) in order to access the right set of stubs.

(aside: it looks like there is no <stdio.h> after your #include...I'm
guessing this is a formatting error or typo).

[1]
http://www.yoctoproject.org/docs/1.7.1/mega-manual/mega-manual.html#optionally-building-a-toolchain-installer

**Comment by 17twenty** [comment]
That makes sense I guess due to the tunables requirements but typically I've found toolchains already "do the right thing" and simply need to add them to the path. Thanks for following up!

And yes, the stdio thing just got omitted from the ticket.

**Comment by 17twenty** [comment]
Just an update on this one, from the generated SDK I have tried to build busybox for the target and found that the compilation doesn't work, nor does the CC=$CC trick.

```
nick@ihatelife:~/Projects/busybox-1.23.1$ CC=$CC make
  CC      applets/applets.o
In file included from /opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi/usr/include/features.h:389:0,
                 from /opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi/usr/include/limits.h:25,
                 from /opt/poky/1.7.1/sysroots/i686-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.9.1/include-fixed/limits.h:168,
                 from /opt/poky/1.7.1/sysroots/i686-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.9.1/include-fixed/syslimits.h:7,
                 from /opt/poky/1.7.1/sysroots/i686-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.9.1/include-fixed/limits.h:34,
                 from include/platform.h:141,
                 from include/libbb.h:13,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
 # include <gnu/stubs-soft.h>
                             ^
compilation terminated.
make[1]: *** [applets/applets.o] Error 1
make: *** [applets_dir] Error 2
```

Any ideas?

**Comment by 17twenty** [comment]
V=1

```
CC=$CC make V=1
rm -f .kernelrelease
echo 1.23.1 > .kernelrelease
/home/nick/Projects/busybox-1.23.1/scripts/gen_build_files.sh /home/nick/Projects/busybox-1.23.1 /home/nick/Projects/busybox-1.23.1
make -f scripts/Makefile.build obj=scripts/basic
mkdir -p .tmp_versions
rm -f .tmp_versions/*
make -f scripts/Makefile.build obj=applets
  arm-poky-linux-gnueabi-gcc -Wp,-MD,applets/.applets.o.d   -std=gnu99 -Iinclude -Ilibbb  -include include/autoconf.h -D_GNU_SOURCE -DNDEBUG -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D"BB_VER=KBUILD_STR(1.23.1)" -DBB_BT=AUTOCONF_TIMESTAMP  -O2 -pipe -g -feliminate-unused-debug-types -Wall -Wshadow -Wwrite-strings -Wundef -Wstrict-prototypes -Wunused -Wunused-parameter -Wunused-function -Wunused-value -Wmissing-prototypes -Wmissing-declarations -Wno-format-security -Wdeclaration-after-statement -Wold-style-definition -fno-builtin-strlen -finline-limit=0 -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-guess-branch-probability -funsigned-char -static-libgcc -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fno-unwind-tables -fno-asynchronous-unwind-tables -Os     -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(applets)"  -D"KBUILD_MODNAME=KBUILD_STR(applets)" -c -o applets/applets.o applets/applets.c
In file included from /opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi/usr/include/features.h:389:0,
                 from /opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi/usr/include/limits.h:25,
                 from /opt/poky/1.7.1/sysroots/i686-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.9.1/include-fixed/limits.h:168,
                 from /opt/poky/1.7.1/sysroots/i686-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.9.1/include-fixed/syslimits.h:7,
                 from /opt/poky/1.7.1/sysroots/i686-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.9.1/include-fixed/limits.h:34,
                 from include/platform.h:141,
                 from include/libbb.h:13,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
 # include <gnu/stubs-soft.h>
                             ^
compilation terminated.
make[1]: *** [applets/applets.o] Error 1
make: *** [applets_dir] Error 2
```

**Comment by 17twenty** [comment]
Aha! Workaround time:

```
CFLAGS="-march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a8 --sysroot=/opt/poky/1.7.1/sysroots/cortexa8hf-vfp-neon-poky-linux-gnueabi" CC=$CC make V=1
```

It looks like busybox sanitises the CC variable which caused all the ABI stuff to be scrubbed. Passing the meat of the flags in as CFLAGS seems to solve this  but would RFC on this from gumstix guys to see if that's expected?

**Comment by ashcharles** [comment]
The workaround seems reasonable to me---every software package will have
its quirks.  That said:
* any reason not to use the busybox package as built within yocto?(or at
least get hints from the busybox recipe as to the required incantations)
* is it possible to use "make" directly within the SDK environment?
(workarounds might still be needed but I'd expect it os at least pick up
environment variables set by the SDK)

**Comment by 17twenty** [comment]
The issue is that I'm trying to build a minimal rescue rootfs as part of an update strategy that wont form part of the main yocto build. I suppose I could create a sepearate yocto based project but it seems unnecessarily overengineer when I can just do some mkdirs and a make && make install for busybox.

**Comment by ashcharles** [comment]
reasonable to close this issue?  I don't know that Yocto supports the specific desired workflow without a little playing with the CFLAGS/CC variables.

**Comment by 17twenty** [comment]
It can be closed if it's expected behaviour. I did notice on the meta-ti
mailing list that a guy was having the same issue - maybe it's worth
updating the docs to show the difference:

https://lists.yoctoproject.org/pipermail/meta-ti/2015-March/006056.html

**Comment by ashcharles** [comment]
Thanks for pointing to me Chris's question.  It looks like the cmem module he is building has a funky makefile so this is even failing within the bitbake environment (not within SDK).  In either case, the yocto toolchain is configured a specific way so the Makefile for a package built with this toolchain needs to match this.
